### ISSUE TITLE
About MultiWOZ dataset

### ISSUE THREAD

**Issue by ShaneTian** [LooperXX/DF-Net#4]
Can you explain the file structure of the MultiWOZ dataset?
`./data/MULTIWOZ2.1/*.txt`

**Comment by LooperXX** [comment]
We follow the [GLMP](https://github.com/jasonwu0731/GLMP) approach for transformations on the SMD dataset and take the dataset structure of the [MultiWOZ 2.1](https://github.com/budzianowski/multiwoz) dataset into consideration, thus transforming the MultiWOZ 2.1 dataset into what you see as `*.txt`

Each dialogue requires information from {dialogue history in `data.json`, knowledge base in `_db.json` of the corresponding domain and some annotated data in `system_acts.json`} to generate its gold KB. The KB of each dialogue consists of the above Gold KB and several randomly selected KBs.

The KB structure and information for each domain are derived from the WOZ dataset itself, although they may vary slightly between domains

Btw, we only converted the single-domain dialogs in MultiWOZ, and used only some specific domains, because some domains were not present in dev/test, or could not adapt to the converted dataset format.

**Comment by ShaneTian** [comment]
Thank you for your quick reply!

As far as I know, this is the first paper to use `Entity F1` to evaluate MultiWOZ 2.1 (right?).
I want to know how to obtain the entity ground truth (`./data/MULTIWOZ2.1/*.txt`) in the current code? Is it fully aligned with the system action of MultiWOZ 2.1?

**Comment by LooperXX** [comment]
Yes, our paper made the first attempt.
The entity ground truth are based on the knowledge base in `_db.json` of the corresponding domain and some annotated data in `system_acts.json`, but not totally aligned with the system action (we fix some simple errors in the the system action annotation).

**Comment by ShaneTian** [comment]
Thanks a lot!

**Comment by LooperXX** [comment]
You're welcome.
